name: Test pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  deploy_CT_pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install databricks_cli databricks-sdk

      - name: Prepare profile
        run: |
          echo "[DEFAULT]" >> ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg

      - name: Deploy integration test
        id: deploy
        run: |
          python deploy/deploy_pysdk.py  --branch_name ${GITHUB_REF#refs/heads/}  --pr_branch ${GITHUB_REF#refs/heads/}
      
    outputs:
      jobid: ${{ steps.deploy.outputs.JOBID }}
      
  run_CT_pipeline:
    runs-on: ubuntu-latest
    needs:  deploy_CT_pipeline
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
      
    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Use the Output from Previous Job
      run: |
        echo "Received Env Var: ${{ needs.deploy_CT_pipeline.outputs.jobid }}"
        # If you want to use it as an environment variable in a subsequent step:
        echo "JOBID=${{ needs.deploy_CT_pipeline.outputs.jobid }}" >> $GITHUB_ENV
